# Generated by Django 5.0.4 on 2024-04-18 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_circles', '0002_circle_delete_circles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='category',
            field=models.CharField(choices=[('moksline', 'Mokslinė'), ('menine', 'Meninė'), ('sportine', 'Sportinė')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='circle',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_circles.parent'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='children',
            field=models.ManyToManyField(to='manage_circles.child'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
