# Generated by Django 5.0.4 on 2024-04-19 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_circles', '0003_circle_category_circle_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='manage_circles.parent'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Būrelio pavadinimas')),
                ('description', models.TextField(verbose_name='Aprašymas')),
                ('activity_type', models.CharField(choices=[('artistic', 'Meninė'), ('scientific', 'Mokslinė'), ('sports', 'Sportinė')], max_length=50, verbose_name='Veiklos tipas')),
                ('start_time', models.TimeField(verbose_name='Pradžios laikas')),
                ('end_time', models.TimeField(verbose_name='Pabaigos laikas')),
                ('instructor', models.CharField(max_length=100, verbose_name='Vedėjas')),
                ('children', models.ManyToManyField(related_name='clubs', to='manage_circles.child')),
            ],
            options={
                'verbose_name_plural': 'Būreliai',
            },
        ),
        migrations.DeleteModel(
            name='Circle',
        ),
    ]
