# Generated by Django 5.0.4 on 2024-04-19 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_circles', '0004_alter_child_parent_alter_parent_user_club_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={},
        ),
        migrations.RemoveField(
            model_name='club',
            name='children',
        ),
        migrations.RemoveField(
            model_name='club',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='club',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='club',
            name='start_time',
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('group', models.CharField(choices=[('Preschool', 'Priešmokyklinukai'), ('Grades 1-7', 'Pirmokai – septintokai'), ('Preschool - grade 1', 'Priešmokyklinukai - pirmokai'), ('Grades 2-7', 'Antrokai – septintokai'), ('Grades 1-6', 'Pirmokai – šeštokai')], max_length=100)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='manage_circles.club')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='manage_circles.child')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='manage_circles.session')),
            ],
        ),
    ]
