# Generated by Django 5.0.4 on 2024-04-24 10:00

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_circles', '0005_alter_club_options_remove_club_children_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='registration_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
