# Generated by Django 5.0.4 on 2024-04-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_circles', '0006_enrollment_registration_date_alter_club_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Pirmadienis'), ('Tuesday', 'Antradienis'), ('Wednesday', 'Trečiadienis'), ('Thursday', 'Ketvirtadienis'), ('Friday', 'Penktadienis'), ('Saturday', 'Šeštadienis'), ('Sunday', 'Sekmadienis')], max_length=10, verbose_name='Savaitės diena'),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.TimeField(verbose_name='Pabaigos laikas'),
        ),
        migrations.AlterField(
            model_name='session',
            name='group',
            field=models.CharField(choices=[('Preschool', 'Priešmokyklinukai'), ('Grades 1-7', 'Pirmokai – septintokai'), ('Preschool - grade 1', 'Priešmokyklinukai - pirmokai'), ('Grades 2-7', 'Antrokai – septintokai'), ('Grades 1-6', 'Pirmokai – šeštokai'), ('Grades 2-4', 'Antrokai – ketvirtokai'), ('Grades 1-4', 'Pirmokai – ketvirtokai'), ('Grades 5-7', 'Penktokai – septintokai'), ('Grades 5-8', 'Penktokai – aštuntokai'), ('Preschool - grade 8', 'Priešmokyklinukai - aštuntokai'), ('Newcomers and orange belts', 'Naujokai ir oranžiniai diržai'), ('Advanced (from blue stripes) and older newcomers (9+ years old)', 'Pažengę (nuo mėlynų juostelių) ir vyresni naujokai (9+ metų)'), ('Three to four years old', 'Trijų – keturių metų'), ('Five to six years old', 'Penkių – šešių metų'), ('Seven to ten years old', 'Septynių – dešimties metų'), ('Preschool (group 1)', 'Priešmokyklinukai (1 grupė)'), ('Preschool (group 2)', 'Priešmokyklinukai (2 grupė)')], max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.TimeField(verbose_name='Pradžios laikas'),
        ),
    ]
