# Generated by Django 5.0.4 on 2024-04-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_circles', '0009_alter_session_day_of_week_alter_session_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='group',
            field=models.CharField(choices=[('Priešmokyklinukai', 'Priešmokyklinukai'), ('Pirmokai – septintokai', 'Pirmokai – septintokai'), ('Priešmokyklinukai - pirmokai', 'Priešmokyklinukai - pirmokai'), ('Antrokai – septintokai', 'Antrokai – septintokai'), ('Pirmokai – šeštokai', 'Pirmokai – šeštokai'), ('Antrokai – ketvirtokai', 'Antrokai – ketvirtokai'), ('Pirmokai – ketvirtokai', 'Pirmokai – ketvirtokai'), ('Penktokai – septintokai', 'Penktokai – septintokai'), ('Penktokai – aštuntokai', 'Penktokai – aštuntokai'), ('Priešmokyklinukai - aštuntokai', 'Priešmokyklinukai - aštuntokai'), ('Naujokai ir oranžiniai diržai', 'Naujokai ir oranžiniai diržai'), ('Pažengę (nuo mėlynų juostelių) ir vyresni naujokai (9+ metų)', 'Pažengę (nuo mėlynų juostelių) ir vyresni naujokai (9+ metų)'), ('Trijų – keturių metų', 'Trijų – keturių metų'), ('Penkių – šešių metų', 'Penkių – šešių metų'), ('Septynių – dešimties metų', 'Septynių – dešimties metų'), ('Priešmokyklinukai (1 grupė)', 'Priešmokyklinukai (1 grupė)'), ('Priešmokyklinukai (2 grupė)', 'Priešmokyklinukai (2 grupė)'), ('Visi nuo dešimties metų', 'Visi nuo dešimties metų')], max_length=100),
        ),
    ]
